# Generated by Django 4.1 on 2023-06-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_name_category_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='name',
        ),
    ]
